### ISSUE TITLE
ex9_51.cpp

### ISSUE THREAD

**Issue by aawwsslll** [pezy/Cpp-Primer#154]
std::array<std::string, 12> month_names{"Jan", "Feb", "Mar", "Apr", "May", "Jun",
                                             "Jul", "Aug", "Sep", "Oct","Nov","Dec"};，这句代码在gcc中报错，提示： array must be initialized with a brace-enclosed initializer
和 too many initializers for 'std::array<std::__cxx11::basic_string<char>, 12u>
不放在类内初始化放在构造函数初始化中就正常运行。另外我试了下用vector在类内初始化也没问题，唯独array就报错了。

**Comment by pezy** [comment]
可能是你 g++ 版本太老，我在线试了下，是没问题的: <http://coliru.stacked-crooked.com/a/e7b23040ea28310d>

当然，严格按照 c++11 的标准，这里的初始化应该这样写:

```cpp
std::array<std::string, 12> month_names{{"Jan", "Feb", "Mar", "Apr", "May", "Jun",
"Jul", "Aug", "Sep", "Oct","Nov","Dec"}};
```
或者
```cpp
std::array<std::string, 12> month_names = {"Jan", "Feb", "Mar", "Apr", "May", "Jun",
"Jul", "Aug", "Sep", "Oct","Nov","Dec"};
```

但这样毫无必要的诡异规定，在 c++14 里就废除了。更多参见: https://en.cppreference.com/w/cpp/container/array

**Comment by 1608637229** [comment]
> 
> 
> 可能是你 g++ 版本太老，我在线试了下，是没问题的: http://coliru.stacked-crooked.com/a/e7b23040ea28310d
> 
> 当然，严格按照 c++11 的标准，这里的初始化应该这样写:
> 
> ```c++
> std::array<std::string, 12> month_names{{"Jan", "Feb", "Mar", "Apr", "May", "Jun",
> "Jul", "Aug", "Sep", "Oct","Nov","Dec"}};
> ```
> 
> 或者
> 
> ```c++
> std::array<std::string, 12> month_names = {"Jan", "Feb", "Mar", "Apr", "May", "Jun",
> "Jul", "Aug", "Sep", "Oct","Nov","Dec"};
> ```
> 
> 但这样毫无必要的诡异规定，在 c++14 里就废除了。更多参见: https://en.cppreference.com/w/cpp/container/array

那应该是我的版本太老了。在里面加了{}之后就不报错了。
