### ISSUE TITLE
exercise 3.2的代码可能有错误

### ISSUE THREAD

**Issue by cxs944745612** [pezy/Cpp-Primer#16]
因为题目是说输出text第一段，参见中文版P98（英文版P110）那段代码的注释是说一次输出text的每一行直至遇到第一个空白行为止
您的代码我没有弄错的话，应该是只将第一行字母变成大写，而不是题意中的将第一段变成大写（书中的一段应该指的是直到遇到第一个空白行之前的都算第一段）

我觉得正确的代码应该如下：
int main()
{
	string tempStr;
	vector<string> text;
	while (getline(cin, tempStr))
		 text.push_back(tempStr);
	vector<string>::iterator it;
	for (auto it = text.begin(); it != text.end() && !(*it).empty(); ++it)
		for (auto &c : *it)
			c = toupper(c);
 
	for (auto it = text.begin(); it != text.end(); ++it)
		cout << *it << endl;
        return 0;
}
如果弄错了，抱歉哈！
还有发issue，和pull request是不是没区别，我将你的这个project fork到我自己账户下，那么我在pull request里写这个问题，是不是您也能看到呢？
还有一个小问题，如果将我贴的代码变成代码片，我看我贴上的代码感觉就是纯汉字格式那样（不知道您懂我描述的意思吗）

**Comment by pezy** [comment]
@cxs944745612  感谢你指出Bug，这块的确错会题意了。

issue 与 pull request 是有区别的，可以有空查看一下： https://help.github.com/ 跟着教程走一走。

另外也贴一份中文的：http://www.worldhello.net/gotgithub/04-work-with-others/010-fork-and-pull.html

-----

你说的贴的代码变成了代码片，是因为 Markdown 语法的缘故，可以参考这里：https://help.github.com/articles/markdown-basics/

**Comment by cxs944745612** [comment]
非常感谢，我去看看
