### ISSUE TITLE
第四章习题的一些疑问

### ISSUE THREAD

**Issue by Ocxs** [pezy/Cpp-Primer#17]
### 1.exercise 4.12
`i!=j<k`

你的回答是：if `j<k` is true, means `i != 1`, else means `i != 0`.
但是exercise 4.3 说C++语言没有明确规定大多数二元符的求值顺序，给编译器留有优化的余地。
那么是不是意味着此题还有其他的解法。
如：
if `i!=j` is true,`1<k`,else `0<k`;虽然这样感觉很别扭，但是这种解析方式对不对呢？

### 2.exercise 4.25

which siginifies a negatation operation on that particular bit. The value of that particular bit is then -2147483648. 我觉得可能是拼写有错，siginifies应该是signifies ，negatation应该是negation

### 3.exercise 4.28

这个结果好像是编译器不同，输出结果不一样，`long double` 在vs2013分配的是8字节.

### 4.exercise 4.29

您说的`cout << sizeof(p)/sizeof(*p) << endl;`  的结果依据32bit机器还是64bit机器,这里的machine指的是编译器还是用的电脑呢？我电脑是64位系统，但是用vs2013（32bit版）得到的结果是1。

### 5.exercise 4.31 

>postfix will copy itself as return, then increment or decrement. prefix will increment or decrement first, and return itself. so prefix is more effective in this program.(reduce one copy space.)

您画线的回答有错吗？我觉得没有错误，为何划去呢？

>The postfix operator must store the original value so that it can return the unincremented value as its result. If we don’t need the unincremented value, there’s no need for the extra work done by the postfix operator.

这里不是也说了使用后缀++/--需要存储空间去存储原值，如果后面没有用到该原值，则没有必要使用后缀，所以正如你所说书上给的例子没有体现出区别.书上建议我们使用prefix，但是prefix和postfix还是有区别的，区别就是您画线说的，我这样理解对吗？

### 6.exercise 4.35

在您的注释里说：`ival promoted to double` 我觉得这种说法有点不恰当，不应该用promoted，书上说整形提升，是负责把小整数类型转换成较大的整数类型。short-->int 用promoted比较恰当，int-->double ,是不是用convert更加确切一点呢？毕竟double是浮点型。

我是初读c++primer，如有错误，请见谅！

**Comment by Mooophy** [comment]
> 1.exercise 4.12

@pezy 's answer is correct.
This exercise is talking about **Operator precedence** rather than **Order of Evaluation of Operands**.
```cpp
auto result = i!=j<k
```
Because **Operator precedence** is defined in C++ standard, the code above is equivalent to
```cpp
auto result = i!=(j<k)
```

But because of **Order of Evaluation of Operands** is undefined in standard ,as said in ex4.3. We can't tell `j` or ``k` operand is evaluated first in the expression `j < k`.

**Comment by Mooophy** [comment]
Take the following code as an example :
```cpp
int i = 0;
auto product = ++i * i;
```
The value of variable `product` is undefined, because it's totally depend on compiler implementation. 
It could be `0`, if the right hand side is evaluated first;
It could be `1`, if the left hand side is evaluated first; 
It could be anything else, depending on how compiler is implemented.

**Comment by pezy** [comment]
@Ocxs  抱歉有点忙，你问题又比较多，原谅我一点点的回答哈。

4.12 的确有点问题。`j < k` 的结果是一个 bool 值，与 int 型的 `i` 比较，是会有警告的。本书也不推荐这样的写法：
> **Warning**
> It is usually a **bad idea** to use the boolean literals `true` and `false` as operands in a comparison. These literals should be used only to compare to an object of type `bool`. 

我的答案至少应该把这个写进去。

-----

你说没有明确求职顺序，这点我不敢苟同。我截取书上的顺序表如下：

![unnamed qq screenshot20150225173644](https://cloud.githubusercontent.com/assets/1147451/6368148/e8c117f4-bd14-11e4-99a8-748bb7f18add.png)

可以看到，这是有明确顺序的， `<` 优先于 `!=`。

@Mooophy 还扩展了这个问题，加了一个 `=`. 但我们也可以发现 `=` 比上述两个都靠后。优先级是非常低的。所以其实也不存在 UB 的问题。唯一的问题就在于我最开始提到的 bool 值与 int 值比较的问题。这里会发生自动类型转换，这么写也没什么错。但不推荐。

-----

@Mooophy 举得第二个问题，是很典型的 UB，因为 `++` 与 `*` 是同一个优先级，这与上面的情况有所不同：

![image](https://cloud.githubusercontent.com/assets/1147451/6368432/b047eaee-bd17-11e4-9944-1100e052c87e.png)

非常感谢 @Mooophy 参与讨论。

-----

若这道题无异议的话，我再看看下一个问题哈。 :smile_cat:

**Comment by Mooophy** [comment]
@pezy no problem

**Comment by Ocxs** [comment]
@Mooophy  get it ! Thanks very much !

**Comment by Ocxs** [comment]
@pezy  您说的是对的，我弄错了。谢谢，这些问题有时间抽空回答一下就好，麻烦你了，不好意思！

**Comment by pezy** [comment]
**4.25**

> siginifies应该是signifies ，negatation应该是negation

我也认为有拼写错误。其实这个答案是 Mooophy/Cpp-Primer#140 中修改的，当时我看的不仔细。望 @Mooophy 和 @AlexanderMladenovic 有空可以帮忙确认。 

@Ocxs 感谢你这么认真！

**Comment by pezy** [comment]
> 3.exercise 4.28
> 
> 这个结果好像是编译器不同，输出结果不一样，long double 在vs2013分配的是8字节.

请参考：http://en.wikipedia.org/wiki/Long_double

`long double` 是兼容 C 而来的，原则上它应当比 `double` 更加精细，但 C 标准并未规定其实现。

>On the x86 architecture, most C compilers implement long double as the 80-bit extended precision type supported by x86 hardware (sometimes stored as 12 or 16 bytes to maintain data structure alignment), as specified in the C99 / C11 standards (IEC 60559 floating-point arithmetic (Annex F)). **An exception is Microsoft Visual C++ for x86, which makes long double a synonym for double.**

注意，加重的那个例外就是你说的 VC 编译器。

这都是要看具体实现的。

>Compilers may also use long double for a 128-bit quadruple precision format, which is currently implemented in software.

**Comment by pezy** [comment]
> 这里的machine指的是编译器还是用的电脑呢？

指的是平台，具体到 VS 中，如下图所示：

![image](https://cloud.githubusercontent.com/assets/1147451/6373122/c9a4325a-bd43-11e4-87a7-1b3781d828d9.png)

默认新建的项目是 Win32，可以改为 x64 试一试。

**Comment by pezy** [comment]
> 我这样理解对吗？

对于 4.31， 我之所以更正了答案，是因为看了 http://stackoverflow.com/questions/22591387/usage-of-the-built-in-comma-operator 这个问题和其解答。

简单说，你理解的对。

我仅仅觉得开始的答案有点文不对题，故而扩充了一下，在这个例子里，根本不存在 return 的问题，所以用 prefix 还是 postfix，没有什么区别，仅仅是习惯问题。

**Comment by pezy** [comment]
> int-->double ,是不是用convert更加确切一点呢？毕竟double是浮点型。

yes, you are right. I will fix it.

**Comment by pezy** [comment]
> 我是初读c++primer，如有错误，请见谅！

不要客气，下次如果碰到拼写错误，或是有更好的答案，欢迎直接 pull request.
再次感谢~ :+1:

**Comment by Ocxs** [comment]
Thanks very much for your explanation !

**Comment by Ocxs** [comment]
不敢轻易使用pull request，怕弄错了，发issue可以讨论一下
