### ISSUE TITLE
about 16.2.7

### ISSUE THREAD

**Issue by Layty** [pezy/Cpp-Primer#185]
I can't understand about why t2 is int ?
![](https://blogp.oss-cn-hangzhou.aliyuncs.com/img/20200422113930.png?x-oss-process=style/blog)

**Comment by Layty** [comment]
变量表达式都是左值,虽然不太理解
![](https://blogp.oss-cn-hangzhou.aliyuncs.com/img/20200422114912.png?x-oss-process=style/blog)

**Comment by duncanlou** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Pezy, 我爱你! 求微信!
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                loukangzhi
                            
                    
                        
                            
                                    loukangzhi@outlook.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 04/22/2020 13:13，Layty<notifications@github.com> wrote： 



Closed #185.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
