### ISSUE TITLE
关于第六章习题的一些疑问

### ISSUE THREAD

**Issue by Ocxs** [pezy/Cpp-Primer#20]
## 1.exercise 6.8
```C++
template <typename T> 
T abs(T i)
{
    return i >= 0 ? i : -i;
}
```
题目说的是包含所有函数声明，您写的应该是定义吧？（如果我课本没理解错的话）
但是我在`Chapter6.h`头文件里将您写的上面所示代码拷贝进去，然后又在我的main函数所在的cpp里这样写
```C++
int abs(int i)
{
	return i >= 0 ? i : -i;
}
```
我在想，既然您用模板，那么我直接用int替换成实体，这样算不算重复定义？vs2013编译的时候，第一次，提示错误，说重复定义，但是奇怪的是，第二次编译的时候竟然不报错了，不知道怎么回事，求解答！

另外，您将函数名命名为abs，C++语言中本来就有abs函数，这样写好吗？我测试了一下，编译运行都能过，但是在调用abs函数时，编译器好像调用的是库里的abs函数，而不是我们自己写的。

最后，`int fact(int val)`我在vs2013中是这么写的
```C++
#ifndef int fact(int val)
#endif
```
但是这样写老是会有警告信息，说**"warning C4067:预处理器指令后有意外标记 - 应输入换行符"**，google了一下说**编译器发现预处理器指令之后有多余字符，并忽略它们**，刚开始我写的时候在`fact(int val)`加了`;`，我以为是这原因，将分号删了还有这警告，不知道这是为什么了？说 **ANSI 兼容性 ** ,我只知道这是一种编码方式，但是我是在vs2013里直接写的，又不是在记事本上写的，为什么会出现这种情况呢？我真的无力了。

**Comment by pezy** [comment]
> template <typename T> 
> T abs(T i)
> {
>     return i >= 0 ? i : -i;
> }

This is `template`, out of this chapter. (sorry for that.)

But the question of exercise 6.5:
>Exercise 6.5: Write a function to return the absolute value of its argument.

Doesn't clarify which type of the argument. so in my opinion, `template` is the only way. maybe @Mooophy can give some advices.

------

The other question about Visual Studio 2013, I will respond to you tomorrow. (I don't have windows at home.) :sweat_smile:

**Comment by Mooophy** [comment]
>我在想，既然您用模板，那么我直接用int替换成实体，这样算不算重复定义？vs2013编译的时候，第一次，提示错误，说重复定义，但是奇怪的是，第二次编译的时候竟然不报错了，不知道怎么回事，求解答！

I tried the codes below on vs2012 and qt creator with MinGW4.8.2. No gcc nor clang can be found at hand..

**experiment I**
```cpp
#include <iostream>

template <typename T>
T abs(T i)
{
    std::cout << "template" << std::endl;
    return i >= 0 ? i : -i;
}

int abs(int i)
{
    std::cout << "non template" << std::endl;
    return i >= 0 ? i : -i;
}

int main()
{
    auto result = abs(-1);
    std::cout << result << std::endl;
    return 0;
}
```
Both compiled and output the same thing :
```java
non template
1
```

So the non template version was called.

**experiment II**
```cpp
#include <iostream>

template <typename T>
T abs(T i)
{
    std::cout << "template" << std::endl;
    return i >= 0 ? i : -i;
}

//int abs(int i)
//{
//    std::cout << "non template" << std::endl;
//    return i >= 0 ? i : -i;
//}

int main()
{
    auto result = abs(-1);
    std::cout << result << std::endl;
    return 0;
}
```
Output differed the previous try, but same on two compilers :
```java
1
```
It's reasonable to guess that this time the library version `abs` was called.

**experiment III**
```cpp
#include <iostream>

template <typename T>
T abs_def(T i)
//^^^^^^^<--note the function name had been modified.
{
    std::cout << "template" << std::endl;
    return i >= 0 ? i : -i;
}

//int abs(int i)
//{
//    std::cout << "non template" << std::endl;
//    return i >= 0 ? i : -i;
//}

int main()
{
    auto result = abs_def(-1);
    //            ^^^^^^^

    std::cout << result << std::endl;
    return 0;
}
```
output:
```java
template
1
```
Finally the custom template version `abs` was called.

**Comment by Mooophy** [comment]
A summery copied from [here](http://stackoverflow.com/questions/22411482/c-template-functions-overload-resolution)  

- Nontemplate functions are first-class citizens. A plain old nontemplate function that matches the parameter types as well as any function template will be selected over an otherwise-just-as-good function template.

- If there are no first-class citizens to choose from that are at least as good, then function base templates as the second-class citizens get consulted next. 

For more detail please go through cp5 chapter 16

**Comment by Mooophy** [comment]
> 最后，int fact(int val)我在vs2013中是这么写的
```cpp
#ifndef int fact(int val)
#endif
```

Pretty sure @Ocxs has used macro in a wrong way. Please read something like [this](http://www.cprogramming.com/reference/preprocessor/ifndef.html).

Alternatively, you can try Qt Creator which generates header guards when new header file added. Visual Studio is a great tool, but not for beginners.. 

Hope helps.

**Comment by pezy** [comment]
@Mooophy  Awesome! :+1:  I don't need to say anything more. :smiley_cat:

**Comment by Mooophy** [comment]
~

**Comment by Ocxs** [comment]
@Mooophy Thank you for your advice .:+1:

**Comment by Ocxs** [comment]
@pezy Thank you for your answer in SegmentFault!:+1:
