### ISSUE TITLE
第六章习题的一些疑问

### ISSUE THREAD

**Issue by Ocxs** [pezy/Cpp-Primer#21]
## exercise 6.31
what's the meaning of "preexited"?

## exercise 6.33
In ex6_33_generics_version.cpp:
>````
template<class T>
void vector_print(const vector<T> &_v)
{
    static
           typename vector<T>::const_iterator it = _v.begin();
    cout << *it
            <<" ";
    ++it;
    if(it != _v.end())
    {        
        vector_print(_v);
    }
}

If I tried `void vector_print(const vector<T> _v)` **(not reference)**, it will crash. (Windows + vs2013)  I want to know why . (some tips : `cout << *it++  <<" ";` replace  `    cout << *it  <<" ";   ++it;` ,maybe that's a better idea.)

## Exercise 6.36

`string (&func(string (&arrStr)[10]))[10]` makes it complex .when I read it firstly,I cannot understand it .
Now as far as I know ,I think that `string (&func())[10]` is easy to understand .Function `func` can take 0 parameter .[The right-left rule](http://www.codeproject.com/Articles/7042/How-to-interpret-complex-C-C-declarations?bmkres=success) maybe help beginners like me to understand it.

**Comment by pezy** [comment]
> what's the meaning of "preexited"?

**preexited**: pre + exited --- exist at or from an earlier time.
such as local objects. and example of the book:
```cpp
const string &manip()
{
    string ret;
    // transform ret in some way
    if (!ret.empty())
        return ret;  // WRONG: returning a reference to a local object!
    else
        return "Empty"; // WRONG: "Empty" is a local temporary string
}
```

>Tip
One good way to ensure that the return is safe is to ask: To **what preexisting
object is the reference referring**?
---- Never Return a Reference or Pointer to a Local Object (6.3.2. Functions That Return a Value)

**Comment by pezy** [comment]
> it will crash. (Windows + vs2013) I want to know why

loops endlessly.
check this: http://stackoverflow.com/questions/20184299/how-to-understand-and-fix-the-segmentation-fault-in-this-code

**Comment by pezy** [comment]
> Function func can take 0 parameter

check this question: Mooophy/Cpp-Primer#129 , @Mooophy give very clear explanation.

and check this question: http://stackoverflow.com/questions/26530659/confused-about-array-parameters

You may have more better understanding.

**Comment by Mooophy** [comment]
@Ocxs is a good learner. :+1:

**Comment by Ocxs** [comment]
@pezy  @Mooophy  在SO上问的问题，根据被采纳的答案说的，我将我的理解说一下，您看对不对（英文不是太好）由于static 定义的迭代器it，导致其只会被初始化一次，直到程序结束才会释放。所以在第一次调用`vector_print(_v);`没问题，但是由于`while(cin >> s)`,`s`被push_back到_v，然后就会导致迭代器失效，再次调用`vector_print(_v);`，由于`it`是用static声明的，他只能被初始化一次，所以这叫导致这时候的`it`实际上指的就不是新加元素的`_v`，解引用`it`实际是解引用尾后迭代器，这是非法的在C++语法中？不知道理解的对不对？
Thank you for your explanation ! I got it .(BTW,I had some questions to invite you to answer in segmentfault ,if you have free time ,please help me .Thanks in advance . :+1:

**Comment by Ocxs** [comment]
@Mooophy Thanks ！ I will continue to work hard！ :smile:

**Comment by pezy** [comment]
> 不知道理解的对不对？

对的。就是这样。和你使用 `const vector<T> _v` 导致崩溃，其实大同小异。参数不加引用，第二次递归进入该函数的时候，此`_v`早已不是彼`_v`了。

**Comment by Ocxs** [comment]
@pezy Thanks a lot! :smile:
